<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Report Charts</title>
    <link rel="stylesheet" href="./css/semantic/semantic.min.css">
    <style>
      body {
        background-color: #009688;
      }
      #isd_app {margin-top: 15px};
    </style>
  </head>
  <body>
    <div id="isd_app"></div>
    <script src="http://localhost:8080/public/ishopdesign.min.js"></script>
  </body>
</html>