<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Import Data</title>
    <link rel="stylesheet" href="./css/style.css" />
    <link rel="stylesheet" href="./css/semantic/semantic.min.css">
    <link rel="stylesheet" href="./css/react-table.css">
    <style>
      .order-add-form .ReactTable .rt-td {
        overflow: visible;
      }
      .order-add-form .results.visible {
        max-height: 300px;
        overflow: scroll;
      }
      .order-add-form .visible.dropdown {
        z-index: 20000!important;  
      }
      .order-add-form .header {
        background-image: none;
      }
      .order-add-form .store-item.error .ui input {
        border: 1px solid #F44336;
      }
      .order-add-form .file-upload {
        position: absolute;
        height: 50px;
        z-index: 0;
        width: 100%;
      }
      .order-add-form .file-upload input {
        opacity: 0; 
        height: 50px;
        width: 100%;
      }
      .order-add-form .editable-input {
       overflow: auto; 
      }
      .order-add-form .ui.icon.input input {
        padding-right: 0;
      }
      .order-add-form .ui.input input {
        padding: 4px;
      }
    </style>
  </head>
  <body>
    <div id="isd_app"></div>
    <script>
      window.ISD_BASE_URL = '<?php echo $data['base_url'] ?>/';
      window.ISD_CURRENT_PAGE = '<?php echo isset($_GET['page'])? $_GET['page'] : ''  ?>';
    </script>
    <script src="<?php echo $data['base_url'] ?>/js/vendors.min.js"></script>
    <script src="<?php echo $data['base_url'] ?>/js/lotusimport.min.js"></script>
<!--    <script src="http://localhost:8080/public/ishopdesign.min.js"></script>-->
 
  </body>
</html>