<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Dược phẩm Tuệ Đức | Import Data</title>
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/semantic/semantic.min.css">
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/react-table.css">
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/antd.min.css">
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/style.css" />
  </head>
  <body>
    <div id="isd_app"></div>
    <script>
      window.ISD_BASE_URL = '<?php echo $data['base_url'] ?>/';
      window.ISD_CURRENT_PAGE = '<?php echo isset($_GET['page'])? $_GET['page'] : ''  ?>';
    </script>

    <script src="<?php echo $data['base_url'] ?>/js/vendors.min.js"></script>
    <script src="<?php echo $data['base_url'] ?>/js/lotusimport.min.js"></script>

    <!-- <script src="http://localhost:8080/public/ishopdesign.min.js"></script> -->
  </body>
</html>