<?php 
$serverName = $_SERVER['SERVER_NAME'];
$jsUrl = $data['base_url'];
switch($serverName) {
 case 'localhost':
 case 'erpapp':
 case 'annhien':
 case '127.0.0.1':
   //If webpack server is running, then reference all files from there
   $devServerContent = @file_get_contents('http://localhost:8080/public/ishopdesign.min.js');
   if($devServerContent !== false) {
     $jsUrl = 'http://localhost:8080/public';
   }
   break;
 default:
  $jsUrl = $data['base_url'];
   break;
}
/** End check asset path for developer purpose **/
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Dược phẩm Tuệ Đức | Import Data</title>
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/semantic/semantic.min.css">
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/react-table.css">
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/antd.min.css">
    <link rel="stylesheet" href="<?php echo $data['base_url'] ?>/css/style.css" />
  </head>
  <body>
    <div id="isd_app"></div>
    <script>
      window.ISD_BASE_URL = '<?php echo $data['base_url'] ?>/';
      window.ISD_CURRENT_PAGE = '<?php echo isset($_GET['page'])? $_GET['page'] : ''  ?>';
    </script>
    <?php if(strpos($jsUrl, '8080') !== false) : ?>
    <script src="<?php echo $jsUrl ?>/ishopdesign.min.js"></script>
    <?php else : ?>
    <script src="<?php echo $jsUrl ?>/js/vendors.min.js"></script>
    <script src="<?php echo $jsUrl ?>/js/lotusimport.min.js"></script>
    <?php endif; ?>
  </body>
</html>